name: Metrics
on:
  # Schedule updates (every three days)
  schedule: [{cron: "0 0 */3 * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  # push:
    # branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
        - name: Base
          uses: lowlighter/metrics@latest
          with:
            token: ${{ secrets.METRICS_TOKEN }}
            # template: markdown
            # filename: metrics.svg
            filename: .cache/base.svg
            # config_base64: no
            # filename: README.md
            # config_output: json
            # config_base64: no
            config_timezone: Asia/Tehran
            config_display: large
            # repositories_affiliations: owner, collaborator
            # repositories_forks: yes
            base: header, activity, community, repositories
            # plugin_languages: yes
            # plugin_languages_skipped: CIAvash
            # plugin_languages_details: bytes-size, percentage
            # plugin_languages_limit: 0
            # plugin_languages_sections: most-used, recently-used
            # plugin_languages_indepth: yes
            # plugin_stars: yes
            # plugin_stars_limit: 5
            # plugin_followup: yes

        - name: Languages
          uses: lowlighter/metrics@master
          with:
            token: ${{ secrets.METRICS_TOKEN }}
            filename: .cache/languages.svg
            base: ''
            # config_base64: no
            config_display: large
            config_timezone: Asia/Tehran
            plugin_languages: yes
            plugin_languages_skipped: CIAvash
            plugin_languages_details: bytes-size, percentage
            plugin_languages_limit: 0
            plugin_languages_sections: most-used, recently-used
            plugin_languages_indepth: yes

        - name: Followup
          uses: lowlighter/metrics@latest
          with:
            token: ${{ secrets.METRICS_TOKEN }}
            filename: .cache/followup.svg
            # config_base64: no
            config_display: large
            config_timezone: Asia/Tehran
            base: ''
            plugin_followup: yes
            plugin_followup_sections: user

        - name: Stars
          uses: lowlighter/metrics@latest
          with:
            token: ${{ secrets.METRICS_TOKEN }}
            filename: .cache/stars.svg
            # config_base64: no
            config_display: large
            config_timezone: Asia/Tehran
            base: ''
            plugin_stars: yes
            plugin_stars_limit: 5

        - name: RSS
          uses: lowlighter/metrics@latest
          with:
            token: ${{ secrets.METRICS_TOKEN }}
            template: markdown
            filename: README.md
            config_display: large
            config_timezone: Asia/Tehran
            base: ''
            plugin_rss: yes
            plugin_rss_source: https://www.ciavash.name/blog/atom.xml
            plugin_rss_limit: 5
            # plugin_followup_sections: user
            # plugin_rss: yes
            # plugin_rss_source: https://www.ciavash.name/blog/atom.xml
            # plugin_rss_limit: 5
            # plugin_activity: yes
            # plugin_activity_limit: 5
            # plugin_activity_days: 14
            # plugin_activity_filter: all
