name: Metrics
on:
  # Schedule updates (every three days)
  schedule: [{cron: "0 0 */3 * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  # push:
    # branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: markdown
          # filename: metrics.svg
          filename: README.md
          base: ''
          # config_output: json
          config_base64: no
          config_timezone: Asia/Tehran
          # repositories_affiliations: owner, collaborator
          # repositories_forks: yes
          # plugin_languages: yes
          # plugin_languages_skipped: CIAvash
          # plugin_languages_details: bytes-size, percentage
          # plugin_languages_limit: 0
          # plugin_languages_sections: most-used, recently-used
          # plugin_languages_indepth: yes
          # plugin_stars: yes
          # plugin_stars_limit: 5
          # plugin_followup: yes
          # plugin_followup_sections: user
          plugin_rss: yes
          plugin_rss_source: https://www.ciavash.name/blog/atom.xml
          plugin_rss_limit: 5
          # plugin_activity: yes
          # plugin_activity_limit: 5
          # plugin_activity_days: 14
          # plugin_activity_filter: all
