name: Metrics
on:
  # Schedule updates (start of week)
  schedule: [{cron: "0 0 * * 1"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          config_timezone: Asia/Tehran
          repositories_forks: yes
          plugin_languages: yes
          plugin_languages_skipped: CIAvash
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 0
          plugin_stars: yes
          plugin_stars_limit: 5
          plugin_gists: yes
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_lines: yes
          plugin_rss: yes
          plugin_rss_source: https://blog.ciavash.name/atom.xml
          plugin_rss_limit: 5
